const cartProducts = [
    { "id": 1, "name": "Leather Seat Covers", "category": "Interior", "price": 79.99 },
    { "id": 2, "name": "All-Weather Floor Mats", "category": "Interior", "price": 59.99},
    { "id": 3, "name": "Steering Wheel Cover", "category": "Interior", "price": 19.99 },
    { "id": 4, "name": "Dashboard Cover", "category": "Interior", "price": 29.99 },
    { "id": 5, "name": "Sun Shade", "category": "Interior", "price": 14.99},
    { "id": 6, "name": "Air Freshener", "category": "Interior", "price": 4.99},
    { "id": 7, "name": "Phone Mount", "category": "Interior", "price": 12.99 },
    { "id": 8, "name": "Car Organizer", "category": "Interior", "price": 24.99 },
    { "id": 9, "name": "LED Interior Lighting", "category": "Interior", "price": 39.99 },
    { "id": 10, "name": "Cushion and Neck Pillow Set", "category": "Interior", "price": 34.99 },

    { "id": 11, "name": "Car Cover", "category": "Exterior", "price": 49.99 },
    { "id": 12, "name": "Chrome Trim Kit", "category": "Exterior", "price": 89.99 },
    { "id": 13, "name": "Window Tint Film", "category": "Exterior", "price": 69.99 },
    { "id": 14, "name": "Roof Rack", "category": "Exterior", "price": 199.99 },
    { "id": 15, "name": "License Plate Frame", "category": "Exterior", "price": 14.99},
    { "id": 16, "name": "Mud Flaps", "category": "Exterior", "price": 29.99},
    { "id": 17, "name": "Spoiler", "category": "Exterior", "price": 149.99 },
    { "id": 18, "name": "Body Kit", "category": "Exterior", "price": 499.99 },
    { "id": 19, "name": "Custom Decals", "category": "Exterior", "price": 24.99},
    { "id": 20, "name": "Bull Bar", "category": "Exterior", "price": 249.99 },

    { "id": 21, "name": "Car Stereo", "category": "Electronics", "price": 299.99 },
    { "id": 22, "name": "Speakers", "category": "Electronics", "price": 89.99},
    { "id": 23, "name": "Subwoofer", "category": "Electronics", "price": 199.99 },
    { "id": 24, "name": "Amplifier", "category": "Electronics", "price": 249.99 },
    { "id": 25, "name": "Dash Camera", "category": "Electronics", "price": 99.99 },
    { "id": 26, "name": "GPS Navigation", "category": "Electronics", "price": 159.99 },
    { "id": 27, "name": "Backup Camera", "category": "Electronics", "price": 79.99 },
    { "id": 28, "name": "Car Alarm", "category": "Electronics", "price": 149.99 },
    { "id": 29, "name": "Remote Starter", "category": "Electronics", "price": 199.99 },
    { "id": 30, "name": "Bluetooth Adapter", "category": "Electronics", "price": 29.99},

    { "id": 31, "name": "Performance Air Filter", "category": "Performance", "price": 49.99 },
    { "id": 32, "name": "Exhaust System", "category": "Performance", "price": 499.99 },
    { "id": 33, "name": "Cold Air Intake", "category": "Performance", "price": 299.99 },
    { "id": 34, "name": "Suspension Kit", "category": "Performance", "price": 699.99 },
    { "id": 35, "name": "Brake Pads", "category": "Performance", "price": 99.99 },
    { "id": 36, "name": "Rotors", "category": "Performance", "price": 149.99},
    { "id": 37, "name": "Performance Chip", "category": "Performance", "price": 299.99 },
    { "id": 38, "name": "Spark Plugs", "category": "Performance", "price": 19.99},
    { "id": 39, "name": "Tires", "category": "Performance", "price": 119.99},
    { "id": 40, "name": "Rims", "category": "Performance", "price": 199.99},

    { "id": 41, "name": "LED Headlights", "category": "Lighting", "price": 89.99},
    { "id": 42, "name": "Tail Lights", "category": "Lighting", "price": 99.99},
    { "id": 43, "name": "Fog Lights", "category": "Lighting", "price": 49.99},
    { "id": 44, "name": "Underbody Lights", "category": "Lighting", "price": 129.99 },
    { "id": 45, "name": "Light Bar", "category": "Lighting", "price": 199.99 },
    { "id": 46, "name": "Neon Accent Lights", "category": "Lighting", "price": 69.99 },

    { "id": 47, "name": "Jump Starter", "category": "Utility", "price": 89.99 },
    { "id": 48, "name": "Battery Charger", "category": "Utility", "price": 49.99 },
    { "id": 49, "name": "Tire Pressure Gauge", "category": "Utility", "price": 9.99 },
    { "id": 50, "name": "Emergency Roadside Kit", "category": "Utility", "price": 69.99 }
]

export default cartProducts;